module.exports = {
  __esModule: true,
  documentDirectory: 'file:///mock-document-directory/',
  cacheDirectory: 'file:///mock-cache-directory/',
  bundleDirectory: null,
  getInfoAsync: jest.fn().mockResolvedValue({
    exists: true,
    uri: 'file:///mock-file',
    size: 0,
    isDirectory: false,
  }),
  readAsStringAsync: jest.fn().mockResolvedValue(''),
  writeAsStringAsync: jest.fn().mockResolvedValue(undefined),
  deleteAsync: jest.fn().mockResolvedValue(undefined),
  moveAsync: jest.fn().mockResolvedValue(undefined),
  copyAsync: jest.fn().mockResolvedValue(undefined),
  makeDirectoryAsync: jest.fn().mockResolvedValue(undefined),
  readDirectoryAsync: jest.fn().mockResolvedValue([]),
  downloadAsync: jest.fn().mockResolvedValue({
    uri: 'file:///mock-download',
    status: 200,
    headers: {},
  }),
  uploadAsync: jest.fn().mockResolvedValue({
    body: '',
    headers: {},
    status: 200,
  }),
  createDownloadResumable: jest.fn(),
  createUploadTask: jest.fn(),
  StorageAccessFramework: {
    requestDirectoryPermissionsAsync: jest.fn().mockResolvedValue(null),
    readDirectoryAsync: jest.fn().mockResolvedValue([]),
    makeDirectoryAsync: jest.fn().mockResolvedValue(null),
    createFileAsync: jest.fn().mockResolvedValue(null),
    writeAsStringAsync: jest.fn().mockResolvedValue(undefined),
    deleteAsync: jest.fn().mockResolvedValue(undefined),
  },
};
