/**
 * Auto-generated TypeScript types for environment variables
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is generated by scripts/generate-env-types.js
 * Run 'npm run generate:env-types' to regenerate
 */

export interface EnvVars {
  API_HOST?: string;
  APP_NAME?: string;
  APP_VARIANT?: string;
  GOOGLE_SERVICES_JSON?: string;
  GOOGLE_SERVICES_PLIST?: string;
  KEYCLOAK_CLIENT_ID?: string;
  KEYCLOAK_HOST?: string;
  MAPBOX_DOWNLOADS_TOKEN?: string;
  PACKAGE_NAME?: string;
  [key: string]: string | undefined;
}
