/**
 * Auto-generated TypeScript types for environment variables
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is generated by scripts/generate-env-types.js
 * Run 'npm run generate:env-types' to regenerate
 */

export interface EnvVars {
  APP_NAME?: string;
  APP_VARIANT?: string;
  BASE_URL?: string;
  PACKAGE_NAME?: string;
  [key: string]: string | undefined;
}
